default_platform(:ios)

lane :beta do
  ensure_git_status_clean

  build_number = latest_testflight_build_number(version: get_version_number) + 1
  increment_build_number(
    build_number: build_number
  )

  increment_build_number(build_number: build_number)

  build_app(workspace: "Speedometer.xcworkspace", scheme: "Speedometer")

  upload_to_testflight

  clean_build_artifacts

  reset_git_repo
end
