default_platform(:ios)

before_all do
  ENV["FASTLANE_BUNDLE_ID"] = ENV["FASTLANE_BUNDLE_ID"] || "de.marcelkraus.speedometer"
  ENV["FASTLANE_APPLE_ID"] = ENV["FASTLANE_APPLE_ID"] || "marcel@marcelkraus.de"
end

lane :test do
  run_tests(scheme: "Speedometer")
end

lane :beta do
  test

  date = sh %Q{TZ=Europe/Berlin date +%Y%m%d%H%M}
  increment_build_number(build_number: date)

  build_app(project: "Speedometer.xcodeproj", scheme: "Speedometer")

  upload_to_testflight(skip_waiting_for_build_processing: true)

  clean_build_artifacts
end
