default_platform(:ios)

lane :tests do
  run_tests(scheme: "Speedometer")
end

lane :beta do
  run_tests(scheme: "Speedometer")

  increment_build_number(
    build_number: latest_testflight_build_number(version: get_version_number, initial_build_number: 0) + 1
  )

  build_app(workspace: "Speedometer.xcworkspace", scheme: "Speedometer")

  upload_to_testflight

  clean_build_artifacts
end
